import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AnimatedCursor from "@/components/AnimatedCursor";
import { ThemeProvider } from "next-themes";

// Define Heebo font
const heebo = Heebo({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mohammed Journey",
  description: "Generated by create next app",
  icons: "/window.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={heebo.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <AnimatedCursor />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
